services:
  scheduler:
    build: .
    container_name: scheduler
    environment:
      - APP_VERSION=${APP_VERSION}
    ports:
      - "5678:5678"
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2
    develop:
      watch:
        - path: ./app
          target: /bot/app
          action: rebuild

    command: uv run python -m app.main

  notifier:
    build: .
    container_name: notifier
    environment:
      - SERVICE_TYPE=consumer
      - APP_VERSION=${APP_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2
    command: uv run python -m app.main
