from enum import StrEnum

class MenuType(StrEnum):
    TEACHER = "T"
    TEACHER_STUDENT = "T:S"
    TEACHER_STUDENT_ADD = "T:S:ADD"
    TEACHER_STUDENT_UPDATE = "T:S:UPDATE"
    TEACHER_STUDENT_LIST = "T:S:LIST"
    TEACHER_STUDENT_DELETE = "T:S:DELETE"
    TEACHER_SLOT = "T:SL"
    TEACHER_SLOT_ADD = "T:SL:ADD"
    TEACHER_SLOT_UPDATE = "T:SL:UPDATE"
    TEACHER_SLOT_SPOT = "T:SL:SPOT"
    TEACHER_SLOT_LIST = "T:SL:LIST"
    TEACHER_SLOT_DELETE = "T:SL:DELETE"
    TEACHER_LESSON = "T:L"
    TEACHER_LESSON_ADD = "T:L:ADD"
    TEACHER_LESSON_UPDATE = "T:L:UPDATE"
    TEACHER_LESSON_LIST = "T:L:LIST"
    TEACHER_LESSON_DELETE = "T:L:DELETE"

    STUDENT = "S"
    STUDENT_TEACHER = "S:T"
    STUDENT_TEACHER_LIST = "S:T:LIST"
    STUDENT_SLOT = "S:SL"
    STUDENT_SLOT_LIST = "S:SL:LIST"
    STUDENT_LESSON = "S:L"
    STUDENT_LESSON_LIST = "S:L:LIST"

    ADMIN = "A"
    ADMIN_TEMP = "A:TEMP"
    
    NEW = "NEW"
