from enum import StrEnum


class MenuType(StrEnum):
    TEACHER = "T"
    TEACHER_STUDENT = "T-S"
    TEACHER_SLOT = "T-SL"
    TEACHER_LESSON = "T-L"
    TEACHER_NOTIFICATION = "T-N"
    TEACHER_STATISTICS = "T-ST"
    TEACHER_RECURRENCE = "T-R"
    TEACHER_RESCHEDULE = "T-RS"
    TEACHER_FEEDBACK = "T-FB"
    STUDENT = "S"
    STUDENT_TEACHER = "S-T"
    STUDENT_SLOT = "S-SL"
    STUDENT_LESSON = "S-L"
    STUDENT_SCHEDULE = "S-SCH"
    STUDENT_STATISTICS = "S-ST"
    ADMIN = "A"
    ADMIN_TEMP = "A-TEMP"
    NEW = "NEW"
    CONFIRMATION = "CNFRM"
    CANCEL = "C"
