"""initional revision

Revision ID: 593be3c7b70d
Revises: 
Create Date: 2026-01-07 17:40:23.516441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593be3c7b70d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('is_teacher', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('dt_reg', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dt_edit', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('lessons',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('uuid_teacher', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uuid_teacher'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('slots',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('uuid_teacher', sa.Uuid(), nullable=False),
    sa.Column('dt_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dt_add', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uuid_student', sa.Uuid(), nullable=True),
    sa.Column('dt_spot', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uuid_student'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['uuid_teacher'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid_teacher', 'dt_start', name='_teacher_dt_start_uc')
    )
    op.create_table('teacher_student',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('uuid_teacher', sa.Uuid(), nullable=False),
    sa.Column('uuid_student', sa.Uuid(), nullable=False),
    sa.Column('uuid_lesson', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['uuid_lesson'], ['lessons.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uuid_student'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['uuid_teacher'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid_teacher', 'uuid_student', name='_teacher_student_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_student')
    op.drop_table('slots')
    op.drop_table('lessons')
    op.drop_table('users')
    # ### end Alembic commands ###
