"""initial

Revision ID: d709da0e36b6
Revises: 
Create Date: 2026-01-07 20:09:49.748578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd709da0e36b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('is_teacher', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('dt_reg', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dt_edit', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('lessons',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('id_teacher', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_teacher'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slots',
    sa.Column('id_teacher', sa.Integer(), nullable=False),
    sa.Column('dt_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dt_add', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=True),
    sa.Column('dt_spot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_student'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_teacher'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_teacher', 'dt_start', name='id_teacher_dt_start_uc')
    )
    op.create_table('teacher_student',
    sa.Column('id_teacher', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('id_lesson', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_lesson'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_student'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_teacher'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_teacher', 'id_student', name='id_teacher_student_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_student')
    op.drop_table('slots')
    op.drop_table('lessons')
    op.drop_table('users')
    # ### end Alembic commands ###
