"""empty message

Revision ID: 137db2611e41
Revises: 3a81ac444a34
Create Date: 2026-01-07 23:32:49.354537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '137db2611e41'
down_revision: Union[str, Sequence[str], None] = '3a81ac444a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dt_reg')
    op.drop_column('users', 'dt_edit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dt_edit', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('dt_reg', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
