"""empty message

Revision ID: bb9743769825
Revises: 137db2611e41
Create Date: 2026-01-08 16:45:22.410337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9743769825'
down_revision: Union[str, Sequence[str], None] = '137db2611e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('teacher_student_uuid_lesson_fkey'), 'teacher_student', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_student', 'lessons', ['uuid_lesson'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_student', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_student_uuid_lesson_fkey'), 'teacher_student', 'lessons', ['uuid_lesson'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###
